---- # invariant_enum
----
---- > Non-negotiable operating rules represented as data.
---- > Values read as directives: DO_ for positive imperatives and DO_NOT_ for negative imperatives.
---- > Case-sensitive on the wire.
CREATE TYPE public.invariant_enum AS ENUM (
  'DO_BACKUP_BEFORE_DESTRUCTIVE_OPERATIONS',
  'DO_FOLLOW_PLAN_REVIEW_EDIT_TEST_IMPL_DOC_CYCLE',
  'DO_NOT_BUILD_UNLESS_EXPLICITLY_ASKED',
  'DO_NOT_ECHO_CREDENTIALS_SECRETS_OR_KEYS',
  'DO_NOT_EDIT_N_FILES_WITHOUT_PLAN_REVIEW',
  'DO_NOT_EMBED_BEHAVIOR_OR_STYLE_IN_TEMPLATES',
  'DO_NOT_HEDGE_PROSE',
  'DO_NOT_LEAVE_PARENTHETICALS_AT_LINE_END',
  'DO_NOT_QUERY_OR_MUTATE_STATE_FROM_TEMPLATES',
  'DO_NOT_USE_EM_DASHES',
  'DO_NOT_USE_NULL_EVER',
  'DO_REDACT_HOME_PATHS_FROM_COMMITS',
  'DO_RESPECT_120_COLUMN_WIDTH',
  'DO_RESTART_SHELL_AFTER_ENV_CHANGES',
  'DO_TREAT_SKILLS_AS_PATH_AGNOSTIC'
);
