---- # relation_enum
----
---- > Verbs the recording entity performs.
---- > A memory row reads as entity, relation, target entity, work, and notes.
---- > Case-sensitive on the wire.
CREATE TYPE public.relation_enum AS ENUM (
  'Depends',
  'Creates',
  'Tests',
  'Refactors',
  'Throws',
  'Runs',
  'Guides',
  'Learns',
  'Configures',
  'Thinks',
  'Delivers',
  'Reviews',
  'Documents',
  'Implements',
  'Fixes',
  'Observes',
  'Analyzes',
  'Designs',
  'Encourages',
  'Requests',
  'Reports',
  'Credits',
  'Evolves',
  'Understands',
  'Thanks',
  'Accepts',
  'Imagines',
  'Decodes',
  'Collaborates',
  'Questions',
  'Reflects',
  'Realizes',
  'Integrates',
  'Delegates',
  'Proposes',
  'Researches',
  'Retrospects',
  'Opens',
  'Closes',
  'Receives',
  'Plans',
  'Feedback',
  'Decides'
);
